"""fix created_at теперь правильно отображает время создания

Revision ID: aa7b8d3d8a15
Revises: fda561cffffb
Create Date: 2025-05-20 03:31:26.681002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7b8d3d8a15'
down_revision: Union[str, None] = 'fda561cffffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
